<?php

function mymetatags_permission() {
	return array(
		'manage page meta tags' => array(
			'title' => t('Manage page meta tags'),
			'description' => t('Manage page meta tags.'),
			),
		);
}

function mymetatags_menu() {
	$items['admin/config/search/mymetatags'] = array(
		'page callback' => '_mymetatags_page',
		'file' => 'mymetatags.pages.inc',
		'access arguments' => array('manage page meta tags'),
		'type' => MENU_NORMAL_ITEM,
		);

	$items['“admin/config/search/mymetatags/list'] = array(
		'page callback' => '_mymetatags_page_list',
		'file' => 'mymetatags.pages.inc',
		'type' => MENU_DEFAULT_LOCAL_TASK
	);
	$items['“admin/config/search/mymetatags/update'] = array(
		'page callback' => '_mymetatags_page_update',
		'file' => 'mymetatags.pages.inc',
		'type' => MENU_LOCAL_TASK
	);
	return $items;
}