<?php

function mymetatags_permission() {
	return array(
		'manage page meta tags' => array(
			'title' => t('Manage page meta tags'),
			'description' => t('Manage page meta tags.'),
			),
		);
}

function mymetatags_menu() {
	$items['admin/config/search/mymetatags'] = array(
		'page callback' => '_mymetatags_page',
		'file' => 'mymetatags.pages.inc',
		'access arguments' => array('manage page meta tags'),
		'type' => MENU_NORMAL_ITEM,
		);

	$items['admin/config/search/mymetatags/list'] = array(
		'page callback' => '_mymetatags_page_list',
		'file' => 'mymetatags.pages.inc',
		'access arguments' => array('manage page meta tags'),
		'type' => MENU_DEFAULT_LOCAL_TASK
		);
	$items['admin/config/search/mymetatags/update'] = array(
		'page callback' => '_mymetatags_page_update',
		'file' => 'mymetatags.pages.inc',
		'access arguments' => array('manage page meta tags'),
		'type' => MENU_LOCAL_TASK
		);
	$items['admin/config/search/mymetatags/%mymetatags_map'] = array(
		'page callback' => 'mymetatags_map',
		'page arguments' => array(1),
		'type' => MENU_CALLBACK
		);
	return $items;
}
function mymetatags_map_load($mtid) {
	$query = 'SELECT * FROM {mymetatags}';
	$metas = db_query($query);
	return $metas;
}
function mymetatags_map($m) {
	dpm($m);
	
	return true;
}
function mymetatags_mymetatags_list() {
	return array(
		'description' => 'Descrição do site',
		'google' => 'Configurações do Google',
		'keywords' => 'Palavras chave',
		'robots' => 'Configuração dos robôs'
		);
}

	// $query = 'SELECT * FROM {mymetatags}';
	// $metas = db_query($query);
	// return $metas;

function mymetatags_mymetatags_map($mtid) {
	print_r($mtid);exit;

	return array(
		'front' => array('description', 'google', 'keywords', 'robots'),
		'node' => array('description', 'keywords', 'robots'),

		);
}

function _mymetatags_map($page) {
	return array(
		'description' => 'Teste',
		'keywords' => 'Um, dois, tres'
	);
}
function mymetatags_preprocess_page(&$variables){
	$metas = _mymetatags_map('front');
	foreach ($metas as $name => $content) {
		$element = array(
			'#tag' => 'meta',
			'#attributes' => array( 
				'name' => $name, 
				'content' => $content
			),
		);
		drupal_add_html_head($element, $name);
	}
}